"""
fuzzyschema/ga.py
-----------------
Schema-generic pymoo GA harness for optimising a rule-only chromosome
(see chromosome.py), OR, when `mf_params_cls` is given, a combined
rule+MF chromosome that jointly optimises rules and membership-function
parameters. Application-agnostic: takes an injected
`fitness_fn(chromosome) -> score` to maximise, and (optionally) `rules_fn`
/ `mf_seed_fn` to seed the initial population from an existing expert
configuration.

What this module does NOT do (by design, left to the consuming application):
  - Compute the fitness itself (mAP, MSE, MCC, or anything else). fitness_fn
    receives the raw chromosome array (rule-only, or combined rule+MF when
    mf_params_cls is set) and is entirely responsible for decoding it --
    this module never builds an inference engine or touches ex_fuzzy.
  - Any domain-specific "final verbose evaluation" pass after the GA
    completes -- pass `final_eval_fn` if you want one; it is called with
    (best_chromosome, run_dir) after artefacts are saved.

MF-optimisation mode
---------------------
Pass `mf_params_cls` (a class generated by build_mf_params_class or
build_it2_mf_params_class -- see mf_params.py / mf_params_t2.py) to switch
from a rule-only chromosome to a combined rule+MF chromosome:
  - `mf_params_cls=None` (default): unchanged rule-only behaviour, exactly
    as before this parameter existed.
  - `mf_params_cls=<class>`: the chromosome becomes
    [rule block][MF block] (see chromosome.py's build_combined_chromosome/
    split_combined_chromosome for the exact layout), with MF-block bounds
    derived from mf_chromosome_bounds(mf_params_cls, schema) -- i.e. every
    MF gene's search range is exactly its owning variable's declared
    domain, with no hardcoding.

There is deliberately no separate `optimize_mf_params: bool` flag --
`mf_params_cls` being set *is* the switch, so there's no way for a flag and
a class to disagree with each other.

`mf_seed_fn`, if given, is a callable() -> an instance of mf_params_cls
(e.g. an expert IT2MFParams built via make_it2_from_t1), used to seed the
MF block of individual 0 via its to_vector(). Meaningless without
mf_params_cls also set; passing it alone raises rather than being silently
ignored.

GA design
---------
Backend: pymoo (CPU).
Representation: float-coded with bounds from the chromosome codec (rule
  block) and mf_chromosome_bounds (MF block, when present); rounding inside
  codec.decode converts the rule block to valid integer genes, while the MF
  block stays float (trapezoid breakpoints) all the way through.
Initialisation: first individual seeded from rules_fn / mf_seed_fn (if
  given) via codec.expert_chromosome() / mf_params_cls_instance.to_vector();
  remainder drawn uniformly at random within each block's own bounds.
Crossover: single-point crossover.
Mutation: polynomial mutation per gene.
Selection: tournament selection (pymoo GA default).
"""

from __future__ import annotations

import json
import os
from datetime import datetime
from typing import Any, Callable, Optional, Type

import numpy as np

from fuzzyschema.chromosome import (
    RuleChromosomeCodec, mf_chromosome_bounds,
    build_combined_chromosome, split_combined_chromosome,
)
from fuzzyschema.variable_config import Schema


# ── Human-readable rule export ────────────────────────────────────────────────

def rules_to_readable(schema: Schema, rules: list) -> list:
    """
    Convert a list of RuleSimple objects to a JSON-serialisable list of dicts,
    one key per antecedent variable (with its linguistic label) plus a
    'consequent' key. Sorted by antecedent term indices for deterministic,
    diffable output.
    """
    ant_labels = [[t.label for t in v.terms] for v in schema.antecedents]
    out_labels = [t.label for t in schema.output.terms]

    readable = []
    for rule in rules:
        ants = rule.antecedents
        entry = {
            schema.antecedents[i].name: ant_labels[i][int(ants[i])]
            for i in range(len(schema.antecedents))
        }
        entry['consequent'] = out_labels[int(rule.consequent)]
        readable.append(entry)

    return sorted(
        readable,
        key=lambda r: [schema.antecedents[i].name + '_' + r[schema.antecedents[i].name]
                       for i in range(len(schema.antecedents))],
    )


# ── MF params export ─────────────────────────────────────────────────────────

def _mf_params_to_readable(mf_params) -> dict:
    """
    Convert a decoded MFParams/IT2MFParams instance to a JSON-serialisable
    dict of {field_name: [a, b, c, d]} -- mirrors rules_to_readable's role
    for the MF block, so ga_best_mf_params.json is as inspectable as
    ga_best_rules.json.
    """
    import dataclasses
    return {f.name: list(getattr(mf_params, f.name)) for f in dataclasses.fields(mf_params)}


# ── pymoo problem definition ──────────────────────────────────────────────────

def _make_problem(n_var: int, lower: np.ndarray, upper: np.ndarray,
                   fitness_fn: Callable[[np.ndarray], float]):
    """pymoo minimises by convention, so we negate the fitness: F = -score.

    n_var/lower/upper are passed in already-combined (rule bounds alone, or
    rule bounds concatenated with MF bounds) so this function itself has no
    branching on whether MF-optimisation is active -- that decision is made
    once, by the caller, when it builds these three arguments.
    """
    from pymoo.core.problem import ElementwiseProblem

    class _CombinedProblem(ElementwiseProblem):
        def __init__(self):
            super().__init__(
                n_var=n_var, n_obj=1, xl=lower, xu=upper,
                elementwise_evaluation=True,
            )

        def _evaluate(self, x, out, *args, **kwargs):
            score = fitness_fn(x)
            out['F'] = -score

    return _CombinedProblem()


# ── Seeded sampling ────────────────────────────────────────────────────────────

def _make_sampling(
    codec: RuleChromosomeCodec,
    rules_fn: Optional[Callable[[], list]],
    mf_params_cls: Optional[Type],
    mf_seed_fn: Optional[Callable[[], Any]],
    mf_lower: Optional[np.ndarray],
    mf_upper: Optional[np.ndarray],
    pop_size: int,
    seed: int,
):
    """
    Build the initial population. Rule genes are always drawn as random
    integers in [0, n_consequents] (cast to float, as codec.decode expects).
    When mf_params_cls is set, MF genes are drawn uniformly within each
    gene's own [mf_lower, mf_upper] bound -- i.e. within its variable's
    declared domain, never outside it, even for the random (non-seeded)
    portion of the population.

    Individual 0 is seeded wherever seed material is available: rule block
    from rules_fn (via codec.expert_chromosome), MF block from mf_seed_fn
    (via mf_params_cls_instance.to_vector()) -- independently, so you can
    seed just the rules, just the MF params, both, or neither.
    """
    from pymoo.core.sampling import Sampling

    mf_len = 0 if mf_params_cls is None else len(mf_lower)

    class _ExpertSeededSampling(Sampling):
        def _do(self, problem, n_samples, **kwargs):
            rng = np.random.default_rng(seed)
            rule_part = rng.integers(
                0, codec.n_consequents + 1, size=(n_samples, codec.chrom_len),
            ).astype(float)

            if mf_params_cls is not None:
                mf_part = rng.uniform(mf_lower, mf_upper, size=(n_samples, mf_len))
                X = np.concatenate([rule_part, mf_part], axis=1)
            else:
                X = rule_part

            if rules_fn is not None:
                rule_part[0] = codec.expert_chromosome(rules_fn)
            if mf_params_cls is not None and mf_seed_fn is not None:
                mf_part[0] = mf_seed_fn().to_vector()
            if mf_params_cls is not None:
                X[0] = build_combined_chromosome(rule_part[0], mf_part[0])
            else:
                X[0] = rule_part[0]

            return X

    return _ExpertSeededSampling()


# ── Progress logger ────────────────────────────────────────────────────────────

def _make_callback(codec: RuleChromosomeCodec, rule_len: int, mf_len: int, verbose: bool):
    """
    mf_len is 0 in rule-only mode, in which case split_combined_chromosome's
    slice is a no-op (rule_part == the whole chromosome) -- the logger's
    decode/n_rules logic is identical in both modes, it just always works
    off the rule part specifically rather than assuming the chromosome IS
    the rule part.
    """
    from pymoo.core.callback import Callback

    class _GALogger(Callback):
        def __init__(self):
            super().__init__()
            self.history: list = []

        def notify(self, algorithm):
            F = algorithm.pop.get('F')
            X = algorithm.pop.get('X')

            best_idx = int(F.argmin())
            best_score = float(-F.min())
            mean_score = float(-F.mean())
            best_chrom = X[best_idx]
            rule_part, _ = split_combined_chromosome(best_chrom, rule_len, mf_len)
            n_rules = len(codec.decode(rule_part))

            entry = {
                'gen': algorithm.n_gen,
                'best_score': round(best_score, 6),
                'mean_score': round(mean_score, 6),
                'n_rules': n_rules,
            }
            self.history.append(entry)

            if verbose:
                print(
                    f"Gen {algorithm.n_gen:4d} | best = {best_score:.4f} | "
                    f"mean = {mean_score:.4f} | rules = {n_rules:2d}"
                )

    return _GALogger()


# ── Artefact saving ────────────────────────────────────────────────────────────

def _save_artefacts(run_dir: str, codec: RuleChromosomeCodec, schema: Schema,
                     best_chromosome: np.ndarray, best_score: float,
                     history: list, config: dict,
                     rule_len: int, mf_len: int, mf_params_cls: Optional[Type]) -> None:
    os.makedirs(run_dir, exist_ok=True)

    with open(os.path.join(run_dir, 'ga_config.json'), 'w') as f:
        json.dump(config, f, indent=2)

    np.save(os.path.join(run_dir, 'ga_best_chromosome.npy'), best_chromosome)

    rule_part, mf_part = split_combined_chromosome(best_chromosome, rule_len, mf_len)

    best_rules = codec.decode(rule_part)
    with open(os.path.join(run_dir, 'ga_best_rules.json'), 'w') as f:
        json.dump(
            {
                'score': best_score,
                'n_rules': len(best_rules),
                'rules': rules_to_readable(schema, best_rules),
            },
            f, indent=2,
        )

    # MF params are only decoded/saved when MF-optimisation was active --
    # mf_len == 0 means there is no MF block to decode.
    if mf_params_cls is not None:
        best_mf_params = mf_params_cls.from_vector(mf_part)
        with open(os.path.join(run_dir, 'ga_best_mf_params.json'), 'w') as f:
            json.dump(_mf_params_to_readable(best_mf_params), f, indent=2)

    with open(os.path.join(run_dir, 'ga_history.json'), 'w') as f:
        json.dump(history, f, indent=2)


# ── Public API ─────────────────────────────────────────────────────────────────

def run_ga(
    schema: Schema,
    fitness_fn: Callable[[np.ndarray], float],
    rules_fn: Optional[Callable[[], list]] = None,
    mf_params_cls: Optional[Type] = None,
    mf_seed_fn: Optional[Callable[[], Any]] = None,
    pop_size: int = 30,
    n_gen: int = 50,
    run_name: Optional[str] = None,
    run_dir_base: str = 'runs',
    crossover_prob: float = 0.9,
    mutation_eta: float = 20.0,
    seed: int = 42,
    verbose: bool = True,
    final_eval_fn: Optional[Callable[[np.ndarray, str], Any]] = None,
    extra_config: Optional[dict] = None,
) -> dict:
    """
    Run GA optimisation of a rule-only chromosome (or, with mf_params_cls
    set, a combined rule+MF chromosome) for `schema` and save artefacts.

    Args:
        schema:         Variable schema (antecedents + output) to optimise rules over.
        fitness_fn:     Callable(chromosome) -> float score to MAXIMISE. All
                        application-specific configuration (dataset paths,
                        thresholds, etc.) must already be bound into this
                        closure by the caller. Receives the raw chromosome --
                        rule-only, or combined rule+MF when mf_params_cls is
                        set -- and is entirely responsible for decoding it
                        (via RuleChromosomeCodec.decode / split_combined_chromosome
                        / mf_params_cls.from_vector, as needed).
        rules_fn:       Optional callable() -> list[RuleSimple], the current
                        expert rule base, used to seed individual 0's rule
                        block. If None, the rule block of the initial
                        population is fully random.
        mf_params_cls:  Optional class generated by build_mf_params_class or
                        build_it2_mf_params_class. Setting this is what
                        switches the chromosome from rule-only to combined
                        rule+MF -- there is no separate boolean flag.
                        MF-block bounds are derived from
                        mf_chromosome_bounds(mf_params_cls, schema).
        mf_seed_fn:     Optional callable() -> an mf_params_cls instance
                        (e.g. an expert IT2MFParams), used to seed
                        individual 0's MF block via its to_vector(). Only
                        meaningful alongside mf_params_cls; passing it
                        without mf_params_cls raises ValueError rather than
                        being silently ignored.
        run_name:       Run directory name under run_dir_base/. Auto-generated
                        from a timestamp if not given.
        final_eval_fn:  Optional callable(best_chromosome, run_dir) run once
                        after the GA completes and artefacts are saved --
                        e.g. a verbose, full-pipeline re-evaluation of the
                        best chromosome. Entirely application-specific;
                        this module does not know what it does.
        extra_config:   Extra key/value pairs to record in ga_config.json
                        (e.g. dataset paths) for reproducibility -- purely
                        informational, not used by the GA itself.

    Returns:
        dict with keys: best_chromosome, best_score, best_rules, history,
        run_dir, and (only when mf_params_cls is set) best_mf_params -- the
        decoded mf_params_cls instance for the best chromosome found.
    """
    from pymoo.algorithms.soo.nonconvex.ga import GA
    from pymoo.operators.crossover.pntx import SinglePointCrossover
    from pymoo.operators.mutation.pm import PolynomialMutation
    from pymoo.optimize import minimize

    if mf_seed_fn is not None and mf_params_cls is None:
        raise ValueError(
            "mf_seed_fn was given but mf_params_cls is None -- mf_seed_fn "
            "has nothing to seed. Pass mf_params_cls to enable MF-optimisation "
            "mode, or drop mf_seed_fn if you only want rule-only optimisation."
        )

    codec = RuleChromosomeCodec(schema)
    rule_lower, rule_upper = codec.bounds()

    if mf_params_cls is not None:
        mf_lower, mf_upper = mf_chromosome_bounds(mf_params_cls, schema)
        lower = np.concatenate([rule_lower, mf_lower])
        upper = np.concatenate([rule_upper, mf_upper])
        mf_len = len(mf_lower)
    else:
        mf_lower = mf_upper = None
        lower, upper = rule_lower, rule_upper
        mf_len = 0

    n_var = codec.chrom_len + mf_len

    if run_name is None:
        run_name = f"ga_{datetime.now().strftime('%Y%m%d_%H%M%S')}"
    run_dir = os.path.join(run_dir_base, run_name)
    os.makedirs(run_dir, exist_ok=True)

    config = {
        'run_name': run_name,
        'timestamp': datetime.now().isoformat(timespec='seconds'),
        'pop_size': pop_size,
        'n_gen': n_gen,
        'crossover_prob': crossover_prob,
        'mutation_eta': mutation_eta,
        'seed': seed,
        'chromosome_len': n_var,
        'rule_chromosome_len': codec.chrom_len,
        'mf_chromosome_len': mf_len,
        'optimize_mf_params': mf_params_cls is not None,
        'seeded_from_rules_fn': rules_fn is not None,
        'seeded_from_mf_seed_fn': mf_seed_fn is not None,
        **(extra_config or {}),
    }

    if verbose:
        print(f"\n{'='*60}")
        print("GA Optimisation")
        print(f"  Run:        {run_name}")
        print(f"  Population: {pop_size}  |  Generations: {n_gen}")
        if mf_params_cls is not None:
            print(f"  Chromosome: {n_var} genes ({codec.chrom_len} rule + {mf_len} MF)")
        else:
            print(f"  Chromosome: {n_var} integer genes (rule-only)")
        print(f"  Seed:       {seed}")
        print(f"  Artefacts:  {run_dir}/")
        print(f"{'='*60}\n")

    problem = _make_problem(n_var, lower, upper, fitness_fn)
    sampling = _make_sampling(
        codec, rules_fn, mf_params_cls, mf_seed_fn, mf_lower, mf_upper, pop_size, seed,
    )
    logger = _make_callback(codec, codec.chrom_len, mf_len, verbose)

    algorithm = GA(
        pop_size=pop_size,
        sampling=sampling,
        crossover=SinglePointCrossover(prob=crossover_prob),
        mutation=PolynomialMutation(prob=1.0 / n_var, eta=mutation_eta),
        eliminate_duplicates=True,
    )

    if rules_fn is not None:
        rule_seed = codec.expert_chromosome(rules_fn)
    else:
        rule_seed = np.zeros(codec.chrom_len)
    if mf_params_cls is not None:
        mf_seed = mf_seed_fn().to_vector() if mf_seed_fn is not None else np.zeros(mf_len)
        best_chromosome = build_combined_chromosome(rule_seed, mf_seed)
    else:
        best_chromosome = rule_seed
    best_score = 0.0

    try:
        result = minimize(
            problem, algorithm, termination=('n_gen', n_gen),
            seed=seed, callback=logger, verbose=False,
        )
        best_chromosome = result.X.flatten()
        best_score = float(-result.F.flatten()[0])
    except KeyboardInterrupt:
        if logger.history:
            best_gen_idx = max(
                range(len(logger.history)),
                key=lambda i: logger.history[i]['best_score'],
            )
            if verbose:
                print(f"\n[Interrupted at gen {logger.history[-1]['gen']}]")
                print(f"Best score so far: {logger.history[best_gen_idx]['best_score']:.4f}")

    rule_part, mf_part = split_combined_chromosome(best_chromosome, codec.chrom_len, mf_len)
    best_rules = codec.decode(rule_part)
    best_mf_params = mf_params_cls.from_vector(mf_part) if mf_params_cls is not None else None

    if final_eval_fn is not None:
        if verbose:
            print("\nRunning final evaluation of best chromosome...")
        try:
            final_eval_fn(best_chromosome, run_dir)
        except Exception as e:
            if verbose:
                print(f"  Warning: final evaluation failed ({e}).")

    _save_artefacts(
        run_dir, codec, schema, best_chromosome, best_score, logger.history, config,
        codec.chrom_len, mf_len, mf_params_cls,
    )

    if verbose:
        print(f"\n{'='*60}")
        print("Optimisation complete")
        print(f"  Best score: {best_score:.4f}")
        print(f"  Rules:      {len(best_rules)}")
        print(f"  Artefacts:  {run_dir}/")
        print(f"{'='*60}")

    result_dict = {
        'best_chromosome': best_chromosome,
        'best_score': best_score,
        'best_rules': best_rules,
        'history': logger.history,
        'run_dir': run_dir,
    }
    if mf_params_cls is not None:
        result_dict['best_mf_params'] = best_mf_params
    return result_dict
