"""
fuzzyschema/ga.py
-----------------
Schema-generic pymoo GA harness for optimising a rule-only chromosome
(see chromosome.py), OR, when `mf_params_cls` is given, a combined
rule+MF chromosome that jointly optimises rules and membership-function
parameters. Application-agnostic: takes an injected
`fitness_fn(chromosome) -> score` to maximise, and (optionally) `rules_fn`
/ `mf_seed_fn` to seed the initial population from an existing expert
configuration.

What this module does NOT do (by design, left to the consuming application):
  - Compute the fitness itself (mAP, MSE, MCC, or anything else). fitness_fn
    receives the raw chromosome array (rule-only, or combined rule+MF when
    mf_params_cls is set) and is entirely responsible for decoding it --
    this module never builds an inference engine or touches ex_fuzzy.
  - Any domain-specific "final verbose evaluation" pass after the GA
    completes -- pass `final_eval_fn` if you want one; it is called with
    (best_chromosome, run_dir) after artefacts are saved.

MF-optimisation mode
---------------------
Pass `mf_params_cls` (a class generated by build_mf_params_class or
build_it2_mf_params_class -- see mf_params.py / mf_params_t2.py) to switch
from a rule-only chromosome to a combined rule+MF chromosome:
  - `mf_params_cls=None` (default): unchanged rule-only behaviour, exactly
    as before this parameter existed.
  - `mf_params_cls=<class>`: the chromosome becomes
    [rule block][MF block] (see chromosome.py's build_combined_chromosome/
    split_combined_chromosome for the exact layout), with MF-block bounds
    derived by default from mf_chromosome_bounds(mf_params_cls, schema) --
    i.e. every MF gene's search range is exactly its owning variable's
    declared domain, with no hardcoding.

There is deliberately no separate `optimize_mf_params: bool` flag --
`mf_params_cls` being set *is* the switch, so there's no way for a flag and
a class to disagree with each other.

`mf_bounds_fn` overrides where the MF block's bounds (and hence its LENGTH)
come from. The default, mf_chromosome_bounds, emits exactly 4 bounds per
dataclass field, so mf_len is always n_fields * 4 -- one gene per trapezoid
breakpoint, the raw-breakpoint parameterisation. A codec that optimises
something other than raw breakpoints (e.g. a constrained per-term
shift/scale plus a per-variable FOU-width multiplier) has a chromosome that
is not n_fields * 4 long at all, and cannot be expressed through the default.
Passing mf_bounds_fn(mf_params_cls, schema) -> (lower, upper) frees mf_len
from that shape entirely: nothing else in this module assumes it, since
sampling, mutation, splitting and artefact-saving all take mf_len as a plain
int. The only contract is that mf_params_cls.from_vector accepts a vector of
whatever length the bounds imply.

`mf_seed_fn`, if given, is a callable() -> an instance of mf_params_cls
(e.g. an expert IT2MFParams built via make_it2_from_t1), used to seed the
MF block of individual 0 via its to_vector(). Meaningless without
mf_params_cls also set; passing it alone raises rather than being silently
ignored.

GA design
---------
Backend: pymoo (CPU).
Representation: float-coded with bounds from the chromosome codec (rule
  block) and mf_chromosome_bounds (MF block, when present); rounding inside
  codec.decode converts the rule block to valid integer genes, while the MF
  block stays float (trapezoid breakpoints) all the way through.
Initialisation: first individual seeded from rules_fn / mf_seed_fn (if
  given) via codec.expert_chromosome() / mf_params_cls_instance.to_vector();
  remainder drawn uniformly at random within each block's own bounds.
Crossover: single-point crossover.
Mutation: polynomial mutation, applied to every individual, at a per-gene rate
  of 1/block_len calibrated separately for each block -- 1/rule_len over the
  rule block and 1/mf_len over the MF block, so a longer chromosome does not
  dilute rule-gene mutation pressure. See _make_mutation.
Selection: tournament selection (pymoo GA default).
"""

from __future__ import annotations

import json
import os
import traceback
from datetime import datetime
from typing import Any, Callable, Optional, Type

import numpy as np

from fuzzyschema.chromosome import (
    RuleChromosomeCodec, mf_chromosome_bounds,
    build_combined_chromosome, split_combined_chromosome,
)
from fuzzyschema.variable_config import Schema


# ── Human-readable rule export ────────────────────────────────────────────────

def rules_to_readable(schema: Schema, rules: list) -> list:
    """
    Convert a list of RuleSimple objects to a JSON-serialisable list of dicts,
    one key per antecedent variable (with its linguistic label) plus a
    'consequent' key. Sorted by antecedent term indices for deterministic,
    diffable output.
    """
    ant_labels = [[t.label for t in v.terms] for v in schema.antecedents]
    out_labels = [t.label for t in schema.output.terms]

    readable = []
    for rule in rules:
        ants = rule.antecedents
        entry = {
            schema.antecedents[i].name: ant_labels[i][int(ants[i])]
            for i in range(len(schema.antecedents))
        }
        entry['consequent'] = out_labels[int(rule.consequent)]
        readable.append(entry)

    return sorted(
        readable,
        key=lambda r: [schema.antecedents[i].name + '_' + r[schema.antecedents[i].name]
                       for i in range(len(schema.antecedents))],
    )


# ── MF params export ─────────────────────────────────────────────────────────

def _mf_params_to_readable(mf_params) -> dict:
    """
    Convert a decoded MFParams/IT2MFParams instance to a JSON-serialisable
    dict of {field_name: [a, b, c, d]} -- mirrors rules_to_readable's role
    for the MF block, so ga_best_mf_params.json is as inspectable as
    ga_best_rules.json.
    """
    import dataclasses
    return {f.name: list(getattr(mf_params, f.name)) for f in dataclasses.fields(mf_params)}


# ── Error logging ──────────────────────────────────────────────────────────────

def _log_ga_error(run_dir: str, chromosome: np.ndarray, exc: Exception) -> None:
    """
    Append one JSON line describing a failed fitness_fn call to
    run_dir/ga_errors.jsonl (mode 'a', one write() per line -- no locking
    library needed at this volume). Called from inside _evaluate, which may
    run in a joblib worker process, so this must be self-contained (no
    shared in-memory state) and safe to call from multiple processes
    appending to the same file concurrently.
    """
    entry = {
        'timestamp': datetime.now().isoformat(timespec='seconds'),
        'pid': os.getpid(),
        'chromosome': np.asarray(chromosome).tolist(),
        'exception_type': type(exc).__name__,
        'message': str(exc),
        'traceback': traceback.format_exc(),
    }
    with open(os.path.join(run_dir, 'ga_errors.jsonl'), 'a') as f:
        f.write(json.dumps(entry) + '\n')


# ── pymoo problem definition ──────────────────────────────────────────────────

def _make_problem(n_var: int, lower: np.ndarray, upper: np.ndarray,
                   fitness_fn: Callable[[np.ndarray], float], run_dir: str,
                   elementwise_runner=None):
    """pymoo minimises by convention, so we negate the fitness: F = -score.

    n_var/lower/upper are passed in already-combined (rule bounds alone, or
    rule bounds concatenated with MF bounds) so this function itself has no
    branching on whether MF-optimisation is active -- that decision is made
    once, by the caller, when it builds these three arguments.

    A fitness_fn exception is caught here (not left to crash the run): the
    individual is scored 0.0 and the failure is appended to
    run_dir/ga_errors.jsonl -- one bad chromosome should not lose an entire
    multi-hour GA run, but the failure must still be visible afterwards via
    the failure-rate summary.

    elementwise_runner, when given (a JoblibParallelization instance),
    is passed straight through to pymoo's Problem base. Left at its default
    (None) here, pymoo's own serial LoopedElementwiseEvaluation is used
    instead -- i.e. n_jobs=None in run_ga must reach this function as
    elementwise_runner=None, not some other "serial" sentinel, for
    byte-for-byte backward compatibility with pre-parallelism behaviour.
    """
    from pymoo.core.problem import ElementwiseProblem

    class _CombinedProblem(ElementwiseProblem):
        def __init__(self):
            kwargs = dict(
                n_var=n_var, n_obj=1, xl=lower, xu=upper,
                elementwise_evaluation=True,
            )
            if elementwise_runner is not None:
                kwargs['elementwise_runner'] = elementwise_runner
            super().__init__(**kwargs)

        def _evaluate(self, x, out, *args, **kwargs):
            try:
                score = fitness_fn(x)
            except Exception as exc:
                score = 0.0
                _log_ga_error(run_dir, x, exc)
            out['F'] = -score

    return _CombinedProblem()


# ── Seeded sampling ────────────────────────────────────────────────────────────

def _make_sampling(
    codec: RuleChromosomeCodec,
    rules_fn: Optional[Callable[[], list]],
    mf_params_cls: Optional[Type],
    mf_seed_fn: Optional[Callable[[], Any]],
    mf_lower: Optional[np.ndarray],
    mf_upper: Optional[np.ndarray],
    pop_size: int,
    seed: int,
):
    """
    Build the initial population. Rule genes are always drawn as random
    integers in [0, n_consequents] (cast to float, as codec.decode expects).
    When mf_params_cls is set, MF genes are drawn uniformly within each
    gene's own [mf_lower, mf_upper] bound -- i.e. within its variable's
    declared domain, never outside it, even for the random (non-seeded)
    portion of the population.

    Individual 0 is seeded wherever seed material is available: rule block
    from rules_fn (via codec.expert_chromosome), MF block from mf_seed_fn
    (via mf_params_cls_instance.to_vector()) -- independently, so you can
    seed just the rules, just the MF params, both, or neither.
    """
    from pymoo.core.sampling import Sampling

    mf_len = 0 if mf_params_cls is None else len(mf_lower)

    class _ExpertSeededSampling(Sampling):
        def _do(self, problem, n_samples, **kwargs):
            rng = np.random.default_rng(seed)
            rule_part = rng.integers(
                0, codec.n_consequents + 1, size=(n_samples, codec.chrom_len),
            ).astype(float)

            if mf_params_cls is not None:
                mf_part = rng.uniform(mf_lower, mf_upper, size=(n_samples, mf_len))
                X = np.concatenate([rule_part, mf_part], axis=1)
            else:
                X = rule_part

            if rules_fn is not None:
                rule_part[0] = codec.expert_chromosome(rules_fn)
            if mf_params_cls is not None and mf_seed_fn is not None:
                mf_part[0] = mf_seed_fn().to_vector()
            if mf_params_cls is not None:
                X[0] = build_combined_chromosome(rule_part[0], mf_part[0])
            else:
                X[0] = rule_part[0]

            return X

    return _ExpertSeededSampling()


# ── Progress logger ────────────────────────────────────────────────────────────

def _make_callback(codec: RuleChromosomeCodec, rule_len: int, mf_len: int, verbose: bool):
    """
    mf_len is 0 in rule-only mode, in which case split_combined_chromosome's
    slice is a no-op (rule_part == the whole chromosome) -- the logger's
    decode/n_rules logic is identical in both modes, it just always works
    off the rule part specifically rather than assuming the chromosome IS
    the rule part.
    """
    from pymoo.core.callback import Callback

    class _GALogger(Callback):
        def __init__(self):
            super().__init__()
            self.history: list = []
            # Running best across all generations seen so far, kept separate
            # from `history` (which is JSON-serialised to ga_history.json and
            # must stay chromosome-free) -- this is what a KeyboardInterrupt
            # handler falls back on, since pymoo's own elitism means the
            # best-so-far chromosome may or may not still be in the final
            # population depending on when the interrupt lands.
            self.best_chromosome: Optional[np.ndarray] = None
            self.best_score: float = -np.inf

        def notify(self, algorithm):
            F = algorithm.pop.get('F')
            X = algorithm.pop.get('X')

            best_idx = int(F.argmin())
            best_score = float(-F.min())
            mean_score = float(-F.mean())
            best_chrom = X[best_idx]

            # Decode every individual, not just the best. A best-only n_rules
            # trace cannot distinguish "a rule-pruning mutation was never
            # produced" from "it was produced every generation and always lost
            # to selection" -- the two have completely different remedies, and
            # a flat n_rules line looks identical under both. rule_counts is
            # the population-level observation that separates them.
            #
            # n_rules is taken from rule_counts[best_idx] rather than decoding
            # best_chrom a second time, so the scalar and the vector cannot
            # drift apart.
            rule_counts = [
                len(codec.decode(split_combined_chromosome(x, rule_len, mf_len)[0]))
                for x in X
            ]
            n_rules = rule_counts[best_idx]

            entry = {
                'gen': algorithm.n_gen,
                'best_score': round(best_score, 6),
                'mean_score': round(mean_score, 6),
                'n_rules': n_rules,
                'rule_counts': rule_counts,
            }
            self.history.append(entry)

            if best_score > self.best_score:
                self.best_score = best_score
                self.best_chromosome = np.array(best_chrom, copy=True)

            if verbose:
                print(
                    f"Gen {algorithm.n_gen:4d} | best = {best_score:.4f} | "
                    f"mean = {mean_score:.4f} | rules = {n_rules:2d}"
                )

    return _GALogger()


# ── Artefact saving ────────────────────────────────────────────────────────────

def _save_artefacts(run_dir: str, codec: RuleChromosomeCodec, schema: Schema,
                     best_chromosome: np.ndarray, best_score: float,
                     history: list, config: dict,
                     rule_len: int, mf_len: int, mf_params_cls: Optional[Type]) -> None:
    os.makedirs(run_dir, exist_ok=True)

    with open(os.path.join(run_dir, 'ga_config.json'), 'w') as f:
        json.dump(config, f, indent=2)

    np.save(os.path.join(run_dir, 'ga_best_chromosome.npy'), best_chromosome)

    rule_part, mf_part = split_combined_chromosome(best_chromosome, rule_len, mf_len)

    best_rules = codec.decode(rule_part)
    with open(os.path.join(run_dir, 'ga_best_rules.json'), 'w') as f:
        json.dump(
            {
                'score': best_score,
                'n_rules': len(best_rules),
                'rules': rules_to_readable(schema, best_rules),
            },
            f, indent=2,
        )

    # MF params are only decoded/saved when MF-optimisation was active --
    # mf_len == 0 means there is no MF block to decode.
    if mf_params_cls is not None:
        best_mf_params = mf_params_cls.from_vector(mf_part)
        with open(os.path.join(run_dir, 'ga_best_mf_params.json'), 'w') as f:
            json.dump(_mf_params_to_readable(best_mf_params), f, indent=2)

    with open(os.path.join(run_dir, 'ga_history.json'), 'w') as f:
        json.dump(history, f, indent=2)


# ── Mutation operator ─────────────────────────────────────────────────────────

# Per-individual mutation gate (pymoo's Mutation.prob). 1.0 = every individual
# is mutated, so the per-gene rate (prob_var, set per block below) is the only
# thing controlling mutation pressure. See _make_mutation for why this is not
# left at pymoo's 0.9 default and, in particular, why it must not be set to
# 1/n_var.
_MUTATION_PROB = 1.0


def _make_mutation(rule_len: int, mf_len: int, eta: float, prob: float = _MUTATION_PROB):
    """
    Build the GA's mutation operator.

    pymoo's two mutation probabilities, which are easy to conflate:

      * `prob`     -- the per-INDIVIDUAL gate. Mutation.do() draws
                      `mut = random_state.random(n_individuals) <= prob` and
                      only writes the mutated genes back for the individuals
                      that pass it.
      * `prob_var` -- the per-GENE rate, applied within an individual that
                      passed the gate. Mutation.get_prob_var() already defaults
                      it to min(0.5, 1/problem.n_var) when it isn't given.

    This call site used to construct PolynomialMutation(prob=1.0/n_var), which
    reads as "mutate each gene with probability 1/n_var" but actually sets the
    per-individual gate to 1/n_var while leaving the per-gene rate at its
    1/n_var default. The two then multiply: the effective per-gene rate was
    ~(1/n_var)**2, i.e. ~100x below nominal for an 81-gene rule-only chromosome
    (measured 0.000121 against a nominal 1/81 = 0.0123) and ~500x below nominal
    for a 217-gene combined one. Mutation was effectively switched off in both
    modes. Hence `prob` defaults to 1.0 here (mutate every individual) and the
    per-gene rate is passed separately and explicitly.

    Rule-only mode (mf_len == 0) uses a stock PolynomialMutation with an
    explicit per-gene prob_var of 1/rule_len.

    Combined rule+MF mode (mf_len > 0) needs a per-BLOCK per-gene rate, which
    pymoo has no native support for: mut_pm's own `prob` argument (per-gene,
    unlike Mutation's) is one scalar per individual, broadcast identically
    across every gene column (see pymoo.operators.crossover.binx.mut_binomial).
    A single shared per-gene rate of 1/n_var would give the 81 rule genes
    1/217 instead of 1/81 -- a 2.7x cut in rule-gene mutation pressure that is
    a side effect of the chromosome getting longer, not a deliberate choice.
    So the two blocks are mutated in separate mut_pm calls, each with its own
    per-gene rate (1/rule_len and 1/mf_len), giving each block the rate it
    would have if it were the only thing being optimised, rather than making
    the two compete for one shared budget.

    at_least_once=False matches PolynomialMutation's own default and is the
    correct choice for a per-gene-rate model: it leaves P(>=1 rule-gene
    mutation) at 1-(1-1/rule_len)**rule_len (~0.63 for rule_len=81) rather
    than forcing every individual to take at least one mutation in every block.
    """
    from pymoo.core.mutation import Mutation
    from pymoo.operators.mutation.pm import PolynomialMutation, mut_pm

    if mf_len == 0:
        return PolynomialMutation(prob=prob, prob_var=1.0 / rule_len, eta=eta)

    class _BlockChunkedPolynomialMutation(Mutation):
        def __init__(self):
            super().__init__(prob=prob)
            self.rule_len = rule_len
            self.mf_len = mf_len
            self.eta = eta
            self.rule_prob = 1.0 / rule_len
            self.mf_prob = 1.0 / mf_len

        def _do(self, problem, X, params=None, *args, random_state=None, **kwargs):
            X = X.astype(float)
            n = X.shape[0]
            rl = self.rule_len
            eta_arr = np.full(n, self.eta)
            Xp = X.copy()

            # The rule block occupies genes [0, rule_len) and the MF block
            # [rule_len, n_var) -- the layout build_combined_chromosome lays
            # down and run_ga concatenates the bounds in, so these slices of
            # problem.xl/xu line up with these slices of X.
            Xp[:, :rl] = mut_pm(
                X[:, :rl], problem.xl[:rl], problem.xu[:rl], eta_arr,
                np.full(n, self.rule_prob), at_least_once=False,
                random_state=random_state,
            )
            Xp[:, rl:] = mut_pm(
                X[:, rl:], problem.xl[rl:], problem.xu[rl:], eta_arr,
                np.full(n, self.mf_prob), at_least_once=False,
                random_state=random_state,
            )
            return Xp

    return _BlockChunkedPolynomialMutation()


# ── Public API ─────────────────────────────────────────────────────────────────

def run_ga(
    schema: Schema,
    fitness_fn: Callable[[np.ndarray], float],
    rules_fn: Optional[Callable[[], list]] = None,
    mf_params_cls: Optional[Type] = None,
    mf_seed_fn: Optional[Callable[[], Any]] = None,
    mf_bounds_fn: Optional[Callable[[Type, Schema], tuple]] = None,
    pop_size: int = 30,
    n_gen: int = 50,
    run_name: Optional[str] = None,
    run_dir_base: str = 'runs',
    crossover_prob: float = 0.9,
    mutation_eta: float = 20.0,
    seed: int = 42,
    verbose: bool = True,
    final_eval_fn: Optional[Callable[[np.ndarray, str], Any]] = None,
    extra_config: Optional[dict] = None,
    n_jobs: Optional[int] = None,
    smoke_test: bool = True,
    failure_rate_warn_threshold: float = 0.2,
) -> dict:
    """
    Run GA optimisation of a rule-only chromosome (or, with mf_params_cls
    set, a combined rule+MF chromosome) for `schema` and save artefacts.

    Args:
        schema:         Variable schema (antecedents + output) to optimise rules over.
        fitness_fn:     Callable(chromosome) -> float score to MAXIMISE. All
                        application-specific configuration (dataset paths,
                        thresholds, etc.) must already be bound into this
                        closure by the caller. Receives the raw chromosome --
                        rule-only, or combined rule+MF when mf_params_cls is
                        set -- and is entirely responsible for decoding it
                        (via RuleChromosomeCodec.decode / split_combined_chromosome
                        / mf_params_cls.from_vector, as needed).
        rules_fn:       Optional callable() -> list[RuleSimple], the current
                        expert rule base, used to seed individual 0's rule
                        block. If None, the rule block of the initial
                        population is fully random.
        mf_params_cls:  Optional class generated by build_mf_params_class or
                        build_it2_mf_params_class -- or any class exposing
                        from_vector()/to_vector(), when paired with a
                        matching mf_bounds_fn. Setting this is what switches
                        the chromosome from rule-only to combined rule+MF --
                        there is no separate boolean flag. MF-block bounds
                        are derived from mf_chromosome_bounds(mf_params_cls,
                        schema) unless mf_bounds_fn overrides it.
        mf_seed_fn:     Optional callable() -> an mf_params_cls instance
                        (e.g. an expert IT2MFParams), used to seed
                        individual 0's MF block via its to_vector(). Only
                        meaningful alongside mf_params_cls; passing it
                        without mf_params_cls raises ValueError rather than
                        being silently ignored.
        mf_bounds_fn:   Optional callable(mf_params_cls, schema) ->
                        (lower, upper) float arrays, replacing
                        mf_chromosome_bounds as the source of the MF block's
                        bounds AND length. Omit it and the MF block is the
                        raw-breakpoint chromosome (n_fields * 4 genes,
                        bounded by each variable's domain) -- byte-for-byte
                        the previous behaviour. Pass it to optimise a
                        different MF parameterisation whose chromosome is not
                        n_fields * 4 long (see the MF-optimisation section
                        above). Only meaningful alongside mf_params_cls;
                        passing it without mf_params_cls raises ValueError.
        run_name:       Run directory name under run_dir_base/. Auto-generated
                        from a timestamp if not given.
        final_eval_fn:  Optional callable(best_chromosome, run_dir) run once
                        after the GA completes and artefacts are saved --
                        e.g. a verbose, full-pipeline re-evaluation of the
                        best chromosome. Entirely application-specific;
                        this module does not know what it does.
        extra_config:   Extra key/value pairs to record in ga_config.json
                        (e.g. dataset paths) for reproducibility -- purely
                        informational, not used by the GA itself.
        n_jobs:         CPU process-parallelism for fitness evaluation via
                        pymoo's JoblibParallelization. None (default): fully
                        serial, no elementwise_runner passed -- unchanged,
                        byte-for-byte backward-compatible behaviour. An
                        int > 0: that many joblib worker processes. -1: all
                        available cores. Note: joblib's 'loky' backend
                        pickles fitness_fn (via cloudpickle) to ship it to
                        worker processes -- if fitness_fn closes over
                        unpicklable state, that fails at pickle time rather
                        than at fitness-evaluation time; this module does
                        not work around that, it surfaces as-is.
        smoke_test:     When True (default), fitness_fn is called once,
                        synchronously, on the seed chromosome before the
                        pymoo problem/algorithm are built, with no
                        try/except -- a fundamentally broken fitness_fn
                        raises immediately instead of silently producing a
                        full run of meaningless all-zero scores. Skipped
                        automatically if there is no seed chromosome
                        available (both rules_fn and mf_seed_fn are None).
        failure_rate_warn_threshold:
                        If, after the GA completes, the fraction of
                        fitness_fn calls that raised (logged to
                        run_dir/ga_errors.jsonl) exceeds this threshold, a
                        warning is printed (not raised). A parameter, not a
                        hardcoded constant, so callers can tune it per
                        fitness_fn without touching this module.

    Returns:
        dict with keys: best_chromosome, best_score, best_rules, history,
        run_dir, n_failures, failure_rate, and (only when mf_params_cls is
        set) best_mf_params -- the decoded mf_params_cls instance for the
        best chromosome found.

        On failure, individual fitness_fn exceptions are caught per-call
        (scored 0.0) and appended to run_dir/ga_errors.jsonl -- one bad
        chromosome does not abort the run; n_failures/failure_rate in the
        returned dict summarise how many did.
    """
    from pymoo.algorithms.soo.nonconvex.ga import GA
    from pymoo.operators.crossover.pntx import SinglePointCrossover
    from pymoo.optimize import minimize
    from pymoo.parallelization.joblib import JoblibParallelization

    if mf_seed_fn is not None and mf_params_cls is None:
        raise ValueError(
            "mf_seed_fn was given but mf_params_cls is None -- mf_seed_fn "
            "has nothing to seed. Pass mf_params_cls to enable MF-optimisation "
            "mode, or drop mf_seed_fn if you only want rule-only optimisation."
        )
    if mf_bounds_fn is not None and mf_params_cls is None:
        raise ValueError(
            "mf_bounds_fn was given but mf_params_cls is None -- there is no MF "
            "block for it to bound. Pass mf_params_cls to enable MF-optimisation "
            "mode, or drop mf_bounds_fn if you only want rule-only optimisation."
        )

    codec = RuleChromosomeCodec(schema)
    rule_lower, rule_upper = codec.bounds()

    if mf_params_cls is not None:
        # Omitting mf_bounds_fn resolves to mf_chromosome_bounds -- literally
        # the call this line used to make unconditionally, so the default path
        # is unchanged by construction, not by coincidence.
        bounds_fn = mf_bounds_fn if mf_bounds_fn is not None else mf_chromosome_bounds
        mf_lower, mf_upper = bounds_fn(mf_params_cls, schema)
        lower = np.concatenate([rule_lower, mf_lower])
        upper = np.concatenate([rule_upper, mf_upper])
        mf_len = len(mf_lower)
    else:
        mf_lower = mf_upper = None
        lower, upper = rule_lower, rule_upper
        mf_len = 0

    n_var = codec.chrom_len + mf_len

    if run_name is None:
        run_name = f"ga_{datetime.now().strftime('%Y%m%d_%H%M%S')}"
    run_dir = os.path.join(run_dir_base, run_name)
    os.makedirs(run_dir, exist_ok=True)

    config = {
        'run_name': run_name,
        'timestamp': datetime.now().isoformat(timespec='seconds'),
        'pop_size': pop_size,
        'n_gen': n_gen,
        'crossover_prob': crossover_prob,
        'mutation_eta': mutation_eta,
        'mutation_prob': _MUTATION_PROB,
        'rule_mutation_prob_var': 1.0 / codec.chrom_len,
        'mf_mutation_prob_var': (1.0 / mf_len) if mf_len else None,
        'seed': seed,
        'chromosome_len': n_var,
        'rule_chromosome_len': codec.chrom_len,
        'mf_chromosome_len': mf_len,
        'optimize_mf_params': mf_params_cls is not None,
        'seeded_from_rules_fn': rules_fn is not None,
        'seeded_from_mf_seed_fn': mf_seed_fn is not None,
        'custom_mf_bounds_fn': mf_bounds_fn is not None,
        'n_jobs': n_jobs,
        **(extra_config or {}),
    }

    if verbose:
        print(f"\n{'='*60}")
        print("GA Optimisation")
        print(f"  Run:        {run_name}")
        print(f"  Population: {pop_size}  |  Generations: {n_gen}")
        if mf_params_cls is not None:
            print(f"  Chromosome: {n_var} genes ({codec.chrom_len} rule + {mf_len} MF)")
        else:
            print(f"  Chromosome: {n_var} integer genes (rule-only)")
        print(f"  Seed:       {seed}")
        print(f"  Artefacts:  {run_dir}/")
        print(f"{'='*60}\n")

    if rules_fn is not None:
        rule_seed = codec.expert_chromosome(rules_fn)
    else:
        rule_seed = np.zeros(codec.chrom_len)
    if mf_params_cls is not None:
        mf_seed = mf_seed_fn().to_vector() if mf_seed_fn is not None else np.zeros(mf_len)
        best_chromosome = build_combined_chromosome(rule_seed, mf_seed)
    else:
        best_chromosome = rule_seed
    best_score = 0.0

    # Pre-flight smoke test: call fitness_fn once, synchronously, on the seed
    # chromosome, deliberately outside any try/except -- a fundamentally
    # broken fitness_fn should raise here and abort immediately, rather than
    # burning a full run producing meaningless all-zero scores that only
    # surface as a 100% failure rate after the fact. Only meaningful when a
    # seed chromosome actually came from somewhere (rules_fn/mf_seed_fn); an
    # all-zeros default chromosome isn't representative of what the GA will
    # actually evaluate, so there's nothing useful to smoke-test.
    if smoke_test and (rules_fn is not None or mf_seed_fn is not None):
        if verbose:
            print("Running pre-flight smoke test on seed chromosome...")
        fitness_fn(best_chromosome)

    elementwise_runner = JoblibParallelization(n_jobs=n_jobs) if n_jobs is not None else None

    problem = _make_problem(n_var, lower, upper, fitness_fn, run_dir,
                             elementwise_runner=elementwise_runner)
    sampling = _make_sampling(
        codec, rules_fn, mf_params_cls, mf_seed_fn, mf_lower, mf_upper, pop_size, seed,
    )
    logger = _make_callback(codec, codec.chrom_len, mf_len, verbose)

    algorithm = GA(
        pop_size=pop_size,
        sampling=sampling,
        crossover=SinglePointCrossover(prob=crossover_prob),
        mutation=_make_mutation(codec.chrom_len, mf_len, mutation_eta),
        eliminate_duplicates=True,
    )

    try:
        result = minimize(
            problem, algorithm, termination=('n_gen', n_gen),
            seed=seed, callback=logger, verbose=False,
        )
        best_chromosome = result.X.flatten()
        best_score = float(-result.F.flatten()[0])
    except KeyboardInterrupt:
        if logger.best_chromosome is not None:
            best_chromosome = logger.best_chromosome
            best_score = logger.best_score
            if verbose:
                print(f"\n[Interrupted at gen {logger.history[-1]['gen']}]")
                print(f"Best score so far: {best_score:.4f}")

    # Failure-rate reporting: pop_size * n_gen is the number of fitness
    # evaluations the GA *intended* to run -- an approximation (pymoo's
    # eliminate_duplicates and the seeded individual mean the true count can
    # differ slightly), which is acceptable here since this is a summary
    # statistic, not something the GA loop depends on.
    errors_path = os.path.join(run_dir, 'ga_errors.jsonl')
    n_failures = 0
    if os.path.exists(errors_path):
        with open(errors_path) as f:
            n_failures = sum(1 for _ in f)
    total_evals = pop_size * n_gen
    failure_rate = (n_failures / total_evals) if total_evals > 0 else 0.0

    rule_part, mf_part = split_combined_chromosome(best_chromosome, codec.chrom_len, mf_len)
    best_rules = codec.decode(rule_part)
    best_mf_params = mf_params_cls.from_vector(mf_part) if mf_params_cls is not None else None

    if final_eval_fn is not None:
        if verbose:
            print("\nRunning final evaluation of best chromosome...")
        try:
            final_eval_fn(best_chromosome, run_dir)
        except Exception as e:
            if verbose:
                print(f"  Warning: final evaluation failed ({e}).")

    _save_artefacts(
        run_dir, codec, schema, best_chromosome, best_score, logger.history, config,
        codec.chrom_len, mf_len, mf_params_cls,
    )

    if verbose:
        print(f"\n{'='*60}")
        print("Optimisation complete")
        print(f"  Best score: {best_score:.4f}")
        print(f"  Rules:      {len(best_rules)}")
        print(f"  Failures:   {n_failures} ({failure_rate:.1%})")
        print(f"  Artefacts:  {run_dir}/")
        print(f"{'='*60}")

    # Always printed, regardless of verbose: a failure-rate warning is
    # actionable information about run quality, not routine progress
    # logging, so it shouldn't be silenced by verbose=False the way the
    # summary above is.
    if failure_rate > failure_rate_warn_threshold:
        print(
            f"\n{'!' * 60}\n"
            f"WARNING: fitness_fn failure rate {failure_rate:.1%} exceeds "
            f"failure_rate_warn_threshold={failure_rate_warn_threshold:.1%} "
            f"({n_failures} failures / ~{total_evals} evaluations). "
            f"See {errors_path} for details.\n"
            f"{'!' * 60}"
        )

    result_dict = {
        'best_chromosome': best_chromosome,
        'best_score': best_score,
        'best_rules': best_rules,
        'history': logger.history,
        'run_dir': run_dir,
        'n_failures': n_failures,
        'failure_rate': failure_rate,
    }
    if mf_params_cls is not None:
        result_dict['best_mf_params'] = best_mf_params
    return result_dict
