"""
fuzzyschema/unit.py
-------------------
The initializable-unit pattern: FLSUnit bundles a schema + params + rules +
engine factory; HierarchicalFLS composes a sequential list of units.

Neither class reimplements anything -- they compose the existing builders
(mf_params.get_antecedents / mf_params_t2.get_antecedents_t2), engines
(engine.T1FLSEngine / T2FLSEngine), rule validation (rules.validate_rules) and
chromosome codec (chromosome.RuleChromosomeCodec). Application-agnostic: a unit
knows its own schema and nothing about what the schema means.

No shared mutable state
-----------------------
The single most important property here. A GA fitness evaluation calls
run_inference once per candidate chromosome, always with `overrides`/`params`/
`rules` arguments -- so if building an engine mutated the unit's own
default_params or the list returned by default_rules_fn, every subsequent
candidate would be scored against a corrupted baseline, silently, for the whole
run. Hence:

  - build_engine copies the rules list before handing it to ex_fuzzy.
    A shallow copy is sufficient, and this was verified against the installed
    ex_fuzzy rather than assumed: RuleBaseT1.__init__ and RuleBaseT2.__init__
    both do `rules = self.delete_rule_duplicates(rules)`, which builds and
    returns a NEW list, and neither writes any attribute back onto the
    RuleSimple objects themselves.
  - params are only ever read (their trapezoid tuples are passed to FS/IVFS),
    never written.
  - HierarchicalFLS.run_inference works on a copy of the caller's DataFrame and
    returns it; the caller's frame is never modified in place.
"""

from __future__ import annotations

from typing import Any, Callable, Dict, List, Optional, Tuple

import numpy as np
import pandas as pd

from fuzzyschema.chromosome import RuleChromosomeCodec
from fuzzyschema.engine import FLSEngine, T1FLSEngine, T2FLSEngine
from fuzzyschema.mf_params import get_antecedents, get_output_var
from fuzzyschema.mf_params_t2 import get_antecedents_t2, get_output_var_t2
from fuzzyschema.rules import validate_rules
from fuzzyschema.variable_config import Schema

# engine_type -> (antecedent builder, output-var builder, engine class).
# A dict rather than an if/elif so adding an engine variant is a registration,
# not a code change inside FLSUnit -- and so an unknown engine_type is caught
# by a single membership test at construction.
_ENGINE_TYPES: Dict[str, tuple] = {
    't1': (get_antecedents, get_output_var, T1FLSEngine),
    't2': (get_antecedents_t2, get_output_var_t2, T2FLSEngine),
}


class FLSUnit:
    """
    One initializable FLS: a schema, its default MF params, its default rule
    base, and the engine type to run them on.

    A unit is a *configuration*, not a live engine -- build_engine()/
    run_inference() construct a fresh engine per call, optionally with params
    and/or rules substituted for the unit's defaults. That is what lets a GA
    evaluate thousands of candidates against one unit without the unit itself
    ever changing.
    """

    def __init__(
        self,
        name: str,
        schema: Schema,
        engine_type: str,
        mf_params_cls: type,
        default_params: Any,
        default_rules_fn: Callable[[], list],
        fallback_fn: Optional[Callable[[pd.DataFrame], np.ndarray]] = None,
    ) -> None:
        """
        Args:
            name:             identifies the unit in error messages. Note that
                              HierarchicalFLS keys `overrides` by the name in
                              its own units list, not by this one -- see
                              HierarchicalFLS.
            schema:           this unit's variables. Its OUTPUT VariableSpec's
                              name is the DataFrame column HierarchicalFLS
                              writes this unit's scores to.
            engine_type:      't1' or 't2'. Validated here, so a typo fails at
                              construction rather than on the first candidate
                              of a GA run.
            mf_params_cls:    the class generated by build_mf_params_class /
                              build_it2_mf_params_class for `schema`. Held for
                              consumers (mf_chromosome_bounds, from_vector);
                              this class does not decode chromosomes itself.
            default_params:   an instance of mf_params_cls. Never mutated.
            default_rules_fn: callable() -> list[RuleSimple]. Called fresh each
                              time defaults are needed; the returned list is
                              never mutated (see module docstring).
            fallback_fn:      optional. See run_inference for the exact
                              contract. None means a zero-firing row stays NaN.
        """
        if engine_type not in _ENGINE_TYPES:
            raise ValueError(
                f"FLSUnit '{name}': unknown engine_type {engine_type!r}. "
                f"Valid: {sorted(_ENGINE_TYPES)}"
            )

        self.name = name
        self.schema = schema
        self.engine_type = engine_type
        self.mf_params_cls = mf_params_cls
        self.default_params = default_params
        self.default_rules_fn = default_rules_fn
        self.fallback_fn = fallback_fn

    def build_engine(self, params: Any = None, rules: Optional[list] = None) -> FLSEngine:
        """
        Build a fresh engine. params/rules default to this unit's configured
        defaults, and are resolved INDEPENDENTLY -- passing rules alone leaves
        params at the unit's default, and vice versa.

        The rules list is copied before it reaches ex_fuzzy, so neither the
        caller's list nor default_rules_fn()'s output can be mutated by engine
        construction (see module docstring for why a shallow copy suffices).
        """
        params = self.default_params if params is None else params
        rules = self.default_rules_fn() if rules is None else rules

        validate_rules(rules, self.schema)

        build_ants, build_out, engine_cls = _ENGINE_TYPES[self.engine_type]
        return engine_cls(
            antecedents=build_ants(self.schema, params),
            rules=list(rules),
            output_var=build_out(self.schema, params),
        )

    def run_inference(
        self,
        df: pd.DataFrame,
        params: Any = None,
        rules: Optional[list] = None,
    ) -> np.ndarray:
        """
        Build an engine and run it on df[self.schema.input_var_names], returning
        a (len(df),) score array.

        Missing input columns raise ValueError naming them, rather than letting
        a bare pandas KeyError surface from inside the engine.

        NaN (zero-firing) rows:
          - fallback_fn is None  -> the NaN PROPAGATES to the caller unchanged.
            It is deliberately not coerced to 0 and does not raise: a
            zero-firing rule base is information the caller is entitled to see,
            and silently scoring it 0.0 would make a rule-base gap look like a
            confident low score.
          - fallback_fn is set   -> it is called with the zero-firing rows ONLY,
            i.e. df.loc[nan_mask], and must return an array of length
            nan_mask.sum(), aligned positionally with those rows. Any other
            length raises ValueError -- the result is never broadcast,
            truncated or index-aligned. It is not called at all when no row is
            NaN. Receiving only the NaN rows means a fallback structurally
            cannot overwrite a row the rule base did fire on.
        """
        missing = [c for c in self.schema.input_var_names if c not in df.columns]
        if missing:
            raise ValueError(
                f"FLSUnit '{self.name}': DataFrame is missing input column(s) "
                f"{missing}. Required: {self.schema.input_var_names}. "
                f"Available: {list(df.columns)}"
            )

        engine = self.build_engine(params=params, rules=rules)
        X = df[self.schema.input_var_names].to_numpy(dtype=float)
        scores = np.asarray(engine.run_inference(X), dtype=float)

        if self.fallback_fn is None:
            return scores

        nan_mask = np.isnan(scores)
        n_nan = int(nan_mask.sum())
        if n_nan == 0:
            return scores

        fallback = np.asarray(self.fallback_fn(df.loc[nan_mask]), dtype=float)
        if fallback.shape != (n_nan,):
            raise ValueError(
                f"FLSUnit '{self.name}': fallback_fn returned shape "
                f"{fallback.shape}, expected ({n_nan},) -- one value per "
                f"zero-firing row. fallback_fn receives only the NaN rows "
                f"(df.loc[nan_mask]), not the full frame."
            )
        scores[nan_mask] = fallback
        return scores

    def chromosome_codec(self) -> RuleChromosomeCodec:
        """RuleChromosomeCodec(self.schema) -- stateless; a fresh codec each
        call, since the codec derives everything from the schema and holds no
        run state of its own."""
        return RuleChromosomeCodec(self.schema)


class HierarchicalFLS:
    """
    A sequential composition of FLSUnits. Each unit reads its antecedents from
    named DataFrame columns and writes its scores to a column named by its own
    schema's output variable -- so an earlier unit's output column is available
    to a later unit's column_map, which is what makes the chain a chain.

    Sequencing/freezing POLICY (which unit a GA run optimises, which stay at
    their defaults) is the caller's decision, not this class's. This class only
    provides the mechanism: `overrides`.
    """

    def __init__(self, units: List[Tuple[str, FLSUnit, Dict[str, str]]]) -> None:
        """
        Args:
            units: [(unit_name, unit, column_map)], in EXECUTION ORDER.

              unit_name  is the key `overrides` uses. It MUST equal the unit's
                         own FLSUnit.name -- a mismatch raises. The two names
                         are not allowed to drift apart: an override keyed by
                         the unit's own name while the chain keys it by another
                         would simply never be applied, and a silently
                         unapplied override is invisible in a GA's fitness
                         curve. Duplicate names raise for the same reason --
                         they would make an override ambiguous.

              column_map is {schema_antecedent_name: df_column_name}, and is
                         STRICT: it must name every one of the unit schema's
                         antecedents, and nothing else. There is no identity
                         fallback for an antecedent left out -- a typo'd key
                         must fail loudly rather than quietly leave an
                         antecedent reading some other column. The mapped
                         df_column_name may be a raw input column OR an earlier
                         unit's output column.
        """
        seen: set = set()
        for unit_name, unit, column_map in units:
            if unit_name != unit.name:
                raise ValueError(
                    f"HierarchicalFLS: unit name mismatch -- the units list "
                    f"names this unit {unit_name!r}, but its FLSUnit.name is "
                    f"{unit.name!r}. The two must agree: `overrides` is keyed "
                    f"by this name, so a mismatch would leave an override "
                    f"keyed by {unit.name!r} silently unapplied."
                )
            if unit_name in seen:
                raise ValueError(
                    f"HierarchicalFLS: duplicate unit name {unit_name!r} -- "
                    f"unit names must be unique, or an override keyed by that "
                    f"name would be ambiguous."
                )
            seen.add(unit_name)
            _validate_column_map(unit_name, unit, column_map)

        self.units = units

    def run_inference(
        self,
        df: pd.DataFrame,
        overrides: Optional[Dict[str, dict]] = None,
    ) -> pd.DataFrame:
        """
        Run each unit in list order, writing each unit's scores to
        df[unit.schema.output.name] -- so a later unit's column_map can read an
        earlier unit's output column by that name.

        Returns a NEW DataFrame with the output columns added. The caller's df
        is never modified in place.

        Args:
            overrides: {unit_name: {'params': ..., 'rules': ...}}. Substitutes
                params and/or rules for the named units only; every other unit
                runs at its own defaults. This is the freeze-vs-co-optimize
                MECHANISM -- a GA run targeting one unit passes an override for
                just that unit.

                'params' and 'rules' are resolved INDEPENDENTLY: an override of
                {'rules': X} leaves that unit's params at its default, and vice
                versa. Supplying one never requires supplying the other.

                An override naming a unit that isn't in this chain raises, as
                does an unrecognised key inside an override dict -- both are
                typos whose silent effect would be "the override you thought you
                applied simply didn't happen", which is invisible in a GA's
                fitness curve.
        """
        overrides = overrides or {}

        unit_names = {name for name, _, _ in self.units}
        unknown = set(overrides) - unit_names
        if unknown:
            raise ValueError(
                f"HierarchicalFLS: overrides name unknown unit(s) "
                f"{sorted(unknown)}. Known units: {sorted(unit_names)}"
            )
        for unit_name, override in overrides.items():
            bad_keys = set(override) - {'params', 'rules'}
            if bad_keys:
                raise ValueError(
                    f"HierarchicalFLS: override for unit {unit_name!r} has "
                    f"unknown key(s) {sorted(bad_keys)}. Valid keys: "
                    f"['params', 'rules']"
                )

        out = df.copy()
        for unit_name, unit, column_map in self.units:
            override = overrides.get(unit_name, {})

            _check_columns_present(unit_name, unit, column_map, out)
            # The unit sees the full frame plus its schema's antecedent names
            # aliased onto their mapped columns: the engine reads only the
            # antecedents, but a fallback_fn can also reach raw columns outside
            # the unit's schema. assign() returns a new frame -- `out` (and so
            # the caller's df) is not touched.
            frame = out.assign(**{ant: out[col] for ant, col in column_map.items()})

            out[unit.schema.output.name] = unit.run_inference(
                frame,
                params=override.get('params'),
                rules=override.get('rules'),
            )

        return out


def _validate_column_map(unit_name: str, unit: FLSUnit, column_map: Dict[str, str]) -> None:
    """Schema-only checks, done at construction: the map covers exactly this
    unit's antecedents. The df-dependent check (does the mapped column exist?)
    can only run at inference time -- see _check_columns_present."""
    expected = set(unit.schema.input_var_names)
    given = set(column_map)

    missing = expected - given
    if missing:
        raise ValueError(
            f"HierarchicalFLS unit {unit_name!r}: column_map is missing "
            f"antecedent(s) {sorted(missing)}. It must map every antecedent of "
            f"the unit's schema ({sorted(expected)}) -- there is no identity "
            f"fallback."
        )

    unknown = given - expected
    if unknown:
        raise ValueError(
            f"HierarchicalFLS unit {unit_name!r}: column_map has key(s) "
            f"{sorted(unknown)} that are not antecedents of the unit's schema "
            f"({sorted(expected)})."
        )


def _check_columns_present(
    unit_name: str, unit: FLSUnit, column_map: Dict[str, str], df: pd.DataFrame,
) -> None:
    """Raise immediately if a mapped column isn't in the frame this unit is
    about to run on -- including the case where it names an earlier unit's
    output column that the chain never actually produces (e.g. a unit ordered
    before its own producer). Without this, the failure would surface as a bare
    KeyError from pandas, or worse, an all-NaN column downstream."""
    for ant, col in column_map.items():
        if col not in df.columns:
            raise ValueError(
                f"HierarchicalFLS unit {unit_name!r}: column_map maps antecedent "
                f"{ant!r} -> df column {col!r}, which is not in the DataFrame. "
                f"Available columns: {list(df.columns)}"
            )
